spring:
  application:
    name: kstream-product-merge-example

  kafka:
    streams:
      state-dir: ./target/kstream-statestore
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        schema.registry.url: http://localhost:8081
        num.stream.threads: 1

logging:
  level:
    org.springframework.kafka: DEBUG
